export const ADD_ANVENTORY = "ADD_ANVENTORY";
export const GET_ANVERTORY = "GET_ANVERTORY";
export const UPDATE_ANVERTORY = "UPDATE_ANVERTORY";
export const DELETE_ANVERTORY = 'DELETE_ANVERTORY';
export const SELECT_ANVERTORY = 'SELECT_ANVERTORY';
export const CLEAR_ANVERTORY = 'CLEAR_ANVERTORY';
export const DELETE_SELECT_ANVERTORY = 'DELETE_SELECT_ANVERTORY';